analytics: {}
color:
  brandColors:
    - '#A8A8A8'
    - '#000000'
    - '#808880'
    - '#000000'
    - '#000000'
  brandStrength: 0.398648
  lightness: 0.617398
  rhythmicContrast: 0.231418
  saturation: 0.735641
cta: {}
layout_spectrum: 0.429898
name: Mobil Deneme
opengraph: {}
purpose: {}
typography_spectrum: 0.414695
